# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e815ab8f260add78ab2ed96e356dc7f2c551e9905f7f465d7f3a1c40a6e4c562d6e449a0650d36c77f6851a9bf8ec29307b8671bacb3be09ba4c4bfccc1bc982

test:
  secret_key_base: 506e8772630c41f6767d6334ed884ac16073caeb863f5ab199ad0692961e78ca9ca79666a4210bcb63ae27b16d6085da7d0b94ea4476b8bfb19cef1f361af6d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: e815ab8f260add78ab2ed96e356dc7f2c551e9905f7f465d7f3a1c40a6e4c562d6e449a0650d36c77f6851a9bf8ec29307b8671bacb3be09ba4c4bfccc1bc982
  secret_key_base: e815ab8f260add78ab2ed96e356dc7f2c551e9905f7f465d7f3a1c40a6e4c562d6e449a0650d36c77f6851a9bf8ec29307b8671bacb3be09ba4c4bfccc1bc982
